spring:
  application:
    name: licensingservice
  profiles:
    active:
      default
  spring:
    sleuth:
      sampler:
         percentage:  1
  cloud:
    config:
      enabled: true
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
        binder:
          zkNodes: localhost
          brokers: localhost

#        input:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
